### PR TITLE
Added artificial delay that was missing from fiber/react demo.

### PR DESCRIPTION
**Pull request by jthoms1**
The demo that this was originally converted from had an artificially long delay that forced the render time of triangles to be extended.  I have added that it to show how it compares to fiber or react stack.  This should have been in the original source but was overlooked.

### CODE REVIEW

**Comment by peterennis** [comment]
~~Does this mean the demo is fake?~~
There should be some toggle to switch between the different versions,
or separate links with explanation.
~~If the delay can be selected it would help demonstrate effects of~~
~~internet connection speed.~~
Initial wow factor reduced to hmm...

**Comment by drcmda** [comment]
@peterennis nothing to do with internet connection speed. The original demo was created to demonstrate priority scheduling by deliberately increasing render time of the dots, yet it could maintain a steady framerate by giving the overall structure priority.

Just rendering the dots without slowdown makes no sense in this context. You can see how the demo falls apart when you merge this PR: http://stencil-fiber-demo.surge.sh/

**Comment by peterennis** [comment]
@drcmda, Thanks for the heads up. Comment above edited. I will revisit this after testing with the PR link.

**Comment by adamdbradley** [comment]
Great yeah we need more testing in this. On my machine a delay of 0.4 did not have any jank.

**Pull request merged**
